server:
  port:
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username:
    password:
    url:
  #redis集群
  redis:
    host:
    port:
    password:
    timeout: 0
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3

thread:
  #线程数
  num: